spring.application.name=FinSight
spring.mongodb.uri=mongodb://localhost:27017/finsight
spring.mongodb.database=finsight
jwt.secret=6f4d9d1e2a7b3c8f0e5a1d6c9b2f7e4a8d3c6f1b9e2a5d8c7f0b3e6a9d2c5f8
jwt.expiration=86400000